### ISSUE TITLE
Problem installing DSX Desktop On Mac - Siera

### ISSUE THREAD

**Issue by charles2588** [IBMDataScience/DSx-Desktop#1]
![image](https://cloud.githubusercontent.com/assets/5734421/24680686/c37505a6-1946-11e7-856d-0419e7b233cb.png)
I have docker running
![image](https://cloud.githubusercontent.com/assets/5734421/24680704/d8174ae6-1946-11e7-930d-7a89f707d86e.png)

![image](https://cloud.githubusercontent.com/assets/5734421/24719533/f67d22dc-19ee-11e7-910a-ef6264e2b6c3.png)

**Comment by charles2588** [comment]
downloaded Fresh 
![image](https://cloud.githubusercontent.com/assets/5734421/24719484/ceb2aff6-19ee-11e7-9705-afec4f703fe0.png)

This one doesn't even go to 2%

![image](https://cloud.githubusercontent.com/assets/5734421/24719579/14328cfe-19ef-11e7-81ab-a27f1d58b11d.png)

**Comment by Debbani** [comment]
@charles2588 Please can you attach your log file ( /Users/<username>/Library/Application Support/ibm-dsx-desktop/Logs) so that we can diagnose the problem.

**Comment by charles2588** [comment]
i needed to do two things:-

Update kitematic on my Mac to latest which updated my docker version
I also had Oracle virtual machine installed, so for some reason, docker image for dsx-desktop needed to be started manually from oracle virtual machine. When i started it manually the installation proceeded.
