### ISSUE TITLE
Download current notebook as ipynb launches a blank window.

### ISSUE THREAD

**Issue by marichu2** [IBMDataScience/DSx-Desktop#12]
When I click on "File >Download as" or "File >Make a Copy", a new window is launched but it is blank.  I thought it was just the kernel being busy, but I left the window open for about an hour, and nothing showed up.

**Comment by Debbani** [comment]
@marichu2 Please can you download our latest version of DSX Desktop and let us know if you're still running into issues. You'll need to uninstall DSX Desktop from the Settings menu on the right hand corner, and re-install DSX Desktop from: http://datascience.ibm.com/desktop

**Comment by Debbani** [comment]
@marichu2 Closing this issue, please reopen if your problem still persists.
