### ISSUE TITLE
Installation Hangs During File Extraction on Windows 10

### ISSUE THREAD

**Issue by beverast** [IBMDataScience/DSx-Desktop#14]
When the installation process gets to 'Extracting files..' 98% the timer reaches 0 seconds then proceeds to countdown from -56 sec to 0 sec, then -1 min 56 sec down to -1 min, and the same thing happens at -2 min 56 sec and so forth. I've left the program running for an entire day and the behavior never changed. I ran the installation again with elevated privileges and the same issue occurred.

**Comment by nmarkey10** [comment]
Hi @beverast , if you could send me your log file, I could help assess what's going on.  This would be under the help dropdown at the top of our app that says "Open log folder".  Thanks!

**Comment by nmarkey10** [comment]
My suspicion is that you may have an outdated version of Docker.  Please make sure you are using the most current version.  We create a pipeline between our app and Docker and it is critical that the version is up to date.

**Comment by obarrot** [comment]
+1. installation hangs, I've tried 2 times without success

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

![image](https://cloud.githubusercontent.com/assets/15383351/26679296/b5293df8-46d4-11e7-9067-54e80de581e5.png)

**Comment by nmarkey10** [comment]
@obarrot is the issue surfacing from the images being extracted or is it hanging on the download?  These might be two separate issues.  If you could send me your log file under the Help dropdown I could more easily assess what's going on.

**Comment by ucbdiaz2015** [comment]
Closed this as it's an older issue. If you encounter a similar issue on a newer version of DSX Desktop, please open a new issue.
