### ISSUE TITLE
DSX desktop install is hanging in windows 7 maching

### ISSUE THREAD

**Issue by gathanki** [IBMDataScience/DSx-Desktop#16]
[2017-06-08 09:04:24:0275] [debug] Received bytes: 215769088, filename: DockerToolbox.exe
[2017-06-08 09:04:24:0275] [debug] Received bytes: 215769088, filename: DockerToolbox.exe
[2017-06-08 09:04:27:0531] [debug] Received bytes: 215769088, filename: DockerToolbox.exe
[2017-06-08 09:04:27:0536] [info] Download successfully
[2017-06-08 09:04:27:0536] [info] save path: C:\Users\IBM_ADMIN\Downloads/DockerToolbox.exe
[2017-06-08 09:04:27:0536] [debug] #dl-docker-util: received download path from main process:
[2017-06-08 09:04:27:0537] [debug] C:\Users\IBM_ADMIN\Downloads/DockerToolbox.exe
[2017-06-08 09:04:27:0543] [debug] Docker download completed
[2017-06-08 09:08:15:0824] [info] Creating a docker machine
[2017-06-08 09:08:15:0826] [debug] Running command: docker-machine create --driver virtualbox --virtualbox-disk-size "24000" ibm-dsx
[2017-06-08 09:08:15:0827] [debug] Running Winbox Command with feedback: docker-machine create --driver virtualbox --virtualbox-disk-size "24000" ibm-dsx
[2017-06-08 09:08:16:0129] [debug] #dl-docker-util: cleaning up of C:\Users\IBM_ADMIN\Downloads/DockerToolbox.exe: true
[2017-06-08 09:13:44:0261] [debug] Run Winbox Command Error: Error creating machine: Error in driver during machine creation: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

[2017-06-08 09:13:44:0263] [debug] #CREATE Result: Error creating machine: Error in driver during machine creation: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

for over 20 mins

**Comment by Debbani** [comment]
@gathanki You're required to turn your virtualization on.
Please refer to our documentation:
https://datascience.ibm.com/docs/content/desktop/requirements.html. 

What version of Windows are you on?

**Comment by gathanki** [comment]
Windows 7


                                                                                   
 Best Regards,                                                                     
                                                                                   
 Giridhar (Giri) Athanki                                                           
 Sr. Solution Architect                                                            
 Cognitive/Analytics/IoT/Watson                                                    
 North America Analytics Center (NAAC)                                             
                                                                                   
                                                                                    
                                                                                    
                                                                                    
 Mobile: 614 420 4983                                                           IBM 
 E-mail: gathank@us.ibm.com                                                         
                                                                   6060 Britton pwy 
                                                                   Dublin, OH 43016 
                                                                      United States 
                                                                                    







From:	Debbani <notifications@github.com>
To:	IBMDataScience/DSx-Desktop <DSx-Desktop@noreply.github.com>
Cc:	gathanki <gathank@us.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	06/27/2017 06:46 PM
Subject:	Re: [IBMDataScience/DSx-Desktop] DSX desktop install is hanging
            in windows 7 maching (#16)



@gathanki You're required to turn your virtualization on.
Please refer to our documentation:
https://datascience.ibm.com/docs/content/desktop/requirements.html.


What version of Windows are you on?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Debbani** [comment]
@gathanki Were you able to go to your Bios and enable Virtualization under the Security section? Please launch DSX Desktop after that and continue with the installation.

**Comment by gathanki** [comment]
Thanks it worked.


                                                                                   
 Best Regards,                                                                     
                                                                                   
 Giridhar (Giri) Athanki                                                           
 Sr. Solution Architect                                                            
 Cognitive/Analytics/IoT/Watson                                                    
 North America Analytics Center (NAAC)                                             
                                                                                   
                                                                                    
                                                                                    
                                                                                    
 Mobile: 614 420 4983                                                           IBM 
 E-mail: gathank@us.ibm.com                                                         
                                                                   6060 Britton pwy 
                                                                   Dublin, OH 43016 
                                                                      United States 
                                                                                    







From:	Debbani <notifications@github.com>
To:	IBMDataScience/DSx-Desktop <DSx-Desktop@noreply.github.com>
Cc:	gathanki <gathank@us.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	06/28/2017 12:19 PM
Subject:	Re: [IBMDataScience/DSx-Desktop] DSX desktop install is hanging
            in windows 7 maching (#16)



@gathanki Were you able to go to your Bios and enable Virtualization under
the Security section? Please launch DSX Desktop after that and continue
with the installation.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
