### ISSUE TITLE
IBM Data science desktop stall at 98%  

### ISSUE THREAD

**Issue by shoreshgithub** [IBMDataScience/DSx-Desktop#17]
Hei,I have tried several times to install IBM Data science desktop but after 98% extracting files it will stall definitely.I have even installed and uninstalled new docker for windows.

**Comment by Debbani** [comment]
@shoreshgithub Please can you attach your **dsx-desktop.log** from the **/Users/<username>/Library/Application Support/ibm-dsx-desktop/Logs** directory. You can easily launch the Logs folder by going to the **Help** menu -> **Open log folder**

**Comment by shoreshgithub** [comment]
Hi,I attached file.
I dont have previous version of DSX Desktop but I had anaconda,R,R studio which before installation ibm DSX I unistalled all of them.


[log.txt](https://github.com/IBMDataScience/DSx-Desktop/files/1069113/log.txt)

**Comment by shoreshgithub** [comment]
@Debbani 
I have tried one more time,I installed Docker version 17.03.1-ce-win12 for windows 10 enterprise .I installed oracle virtual box last Version. I put Docker in user varaible path,still stall in extarcting 98% and one time failed at the end of rstudio downloading, in the attched you can find my last logs.
[dsx-desktop-log.txt](https://github.com/IBMDataScience/DSx-Desktop/files/1071162/dsx-desktop-log.txt)

**Comment by shoreshgithub** [comment]
[dsx-desktop-laslog.txt](https://github.com/IBMDataScience/DSx-Desktop/files/1071424/dsx-desktop-laslog.txt)
@Debbani
Here you can find the last log which I tried, no success
![picture folder](https://user-images.githubusercontent.com/29339324/27083211-056bafcc-5048-11e7-9922-1922c3faa91f.PNG)

**Comment by wadeschulz** [comment]
Not sure if it will work in every case, but I had the same issue due to some Docker-related errors. To resolve, the following worked on my installation of Windows 10:
   - Uninstall Docker
   - Using Docker Toolbox and other VirtualBox images in my case, so disabled HyperV
   - Install the newest version of Docker Toolbox (CE did not work in my case)
   - Make sure Docker is turned on and running (launch Kitematic and make sure the image is started in Virtual Box)
   - Relaunch the DSX installer

**Comment by nmarkey10** [comment]
@shoreshgithub We have pinpointed the problem!  When we extract the file we are using a Docker command to import that file as such; "type [filepath] | docker import - [imageName]:[tag]".  The documentation can be seen here https://docs.docker.com/engine/reference/commandline/import/.  

When using Docker Toolbox on Windows or any Docker version on Mac, this command works.  But for some reason, when you use the Native Docker App, it seems to get tripped up.  I have the correct extraction command via trial and error.  This is "docker import [path] [imageName]:[tag]".  There are some subtle changes in syntax and we are no longer piping it to the docker import.  This isn't really documented anywhere, hence the trial and error.  This will be included in our next build.  Your log actually helped a lot to fix this problem!  Thank you for letting us now and staying patient.  We really appreciate it!

**Comment by Debbani** [comment]
@shoreshgithub Please download the latest image (Version 1.1.6) from: https://datascience.ibm.com/desktop which addresses the issue that you were running into during installation.

**Comment by Debbani** [comment]
@shoreshgithub Closing this issue. Please reopen if your problem persists.
