### ISSUE TITLE
After starting only white screen on MacOS Sierra

### ISSUE THREAD

**Issue by romeokienzler** [IBMDataScience/DSx-Desktop#18]
After starting you get only a white screen on MacOS Sierra, nothing else happens

**Comment by Debbani** [comment]
@romeokienzler When do you see the white screen? Have you already installed DSX Desktop successfully and are then running into blank screen issue? Or did you have an older version of DSX Desktop installed and were trying to upgrade to a later version of DSX Desktop?

**Comment by rodrigoseguelb** [comment]
When I try to Open a Notebook already uploaded via a file, a white screen appear. Please your help

**Comment by romeokienzler** [comment]
@Debbani I've installed it multiple times and directly after starting the white screen appears, nothing else happens....are there some logs?

**Comment by rodrigoseguelb** [comment]
I re-installed everything again, and works now. Thanks!

Rodrigo Seguel
+569 9 549 5766
Sent from iPhone

On Jul 1, 2017, at 13:14, Romeo Kienzler <notifications@github.com<mailto:notifications@github.com>> wrote:


@Debbani<https://github.com/debbani> I've installed it multiple times and directly after starting the white screen appears, nothing else happens....are there some logs?

**Comment by romeokienzler** [comment]
@rodrigoseguelb can you please share your exact MacOS version?

**Comment by rodrigoseguelb** [comment]
10.12.5

Saludos

Rodrigo Seguel
+56 9 9 549 5766




On Jul 1, 2017, at 1:30 PM, Romeo Kienzler <notifications@github.com<mailto:notifications@github.com>> wrote:


@rodrigoseguelb<https://github.com/rodrigoseguelb> can you please share your exact MacOS version?

**Comment by T9876** [comment]
I do have the same problem like @romeokienzler 
when i start Data Science Experience a blank screen appears with nothing else except the menu items 'File', 'View' and 'Help' 
Can you tell me please help me?

**Comment by Debbani** [comment]
@romeokienzler Please remove the **Settings** file from the /Users/[username]/Library/Application Support/ibm-dsx-desktop directory and please retry the installation.

**Comment by Debbani** [comment]
@T9876 The **Settings** file is located in: **%APPDATA%\ibm-dsx-desktop** on Windows if you used the default installation path. Please remove this file and retry the installation.

**Comment by T9876** [comment]
thanks @Debbani 
I had to uninstall every single component (virtualbox,...), then installing DSX again, afterwards removing the settings file and then running the DSX.exe a second time - now it's working !

**Comment by romeokienzler** [comment]
@Debbani thanks, this is fixed, now I've filed the next one:  When creating a new notebook the wheel turns infinitely #23
