### ISSUE TITLE
Linux: When open or create a notebook Swirl keeps turning continuously... 

### ISSUE THREAD

**Issue by willemhendriks** [IBMDataScience/DSx-Desktop#19]
Linux: When open or create a notebook Swirl keeps turning continuously... 

$ docker -v
Docker version 1.10.2, build 0f5ac89/1.10.2

Redhat 7
3.10.0-514.21.1.el7.x86_64 #

**Comment by NateMoeller** [comment]
It looks like you are using an older version of docker. I would recommend updating to the latest version and trying again. If the problem persists, please post your log file and I can look into it further.

Thank you!

**Comment by Debbani** [comment]
@willemhendriks Please reopen this issue if the problem still persists after upgrading to the latest version of Docker.
