### ISSUE TITLE
Why nobody from IBM reply to our questions and problems?

### ISSUE THREAD

**Issue by shoreshgithub** [IBMDataScience/DSx-Desktop#20]
Why nobody from IBM reply to our questions and problems regarding data science experience desktop? I know it is free ,but it would be appriciated some one helps us to install it.
I posted several days ago reagrding stall in extracting file in 98% and still wait to get a help and instruction.

Thnaks

**Comment by Debbani** [comment]
@shoreshgithub Apologize for the delay in getting back to you. We're currently investigating your issue and will respond to you once we've a fix.

**Comment by Debbani** [comment]
@shoreshgithub We've a fix which will be available in the next build. 
Updates will be posted in: https://github.com/IBMDataScience/DSx-Desktop/issues/17
