### ISSUE TITLE
Python library "python-twitter" does not install successfully

### ISSUE THREAD

**Issue by anamecheverri** [IBMDataScience/DSx-Desktop#21]
I created a notebook on dsx cloud.  Downloaded the file and used that file to create a notebook on dsx desktop.

I then installed this library using "!pip install python-twitter".

However something does not work as "import twitter" gives me an error: ImportError: No module named 'twitter'

(This same code works fine on DSX cloud and it works fine if i just create a new notebook from scratch but it gives me an error when using the code from the downloaded notebook)

**Comment by Debbani** [comment]
@anamecheverri Please can you attach the notebook that you're referring to so I can see the error that you're running into. Otherwise, the pip install works on a new notebook created in DSX Desktop.

**Comment by Debbani** [comment]
@anamecheverri Closing this issue for now. Please reopen if you're still running into this issue with our latest version of DSX Desktop.
