### ISSUE TITLE
Haven't been able to install DSX Desktop

### ISSUE THREAD

**Issue by JeremyBloom** [IBMDataScience/DSx-Desktop#22]
As you may know, I'm retiring from IBM this week. I am hoping to continue working with DSX after that. I have made several attempts to install DSX Desktop, both on my IBM laptop (Lenovo W530 with Intel i7 3720 and Windows 7 64-bit) and also my home machine (HP Pavilion with AMD A-10 5745 and Windows 10 Home 64-bit). I have not been successful with any of these attempts.

Installation is a complex process with many steps that can kill it. The download is huge (3 GB with Virtual Box, Docker Toolbox, Kinematic, Anaconda, and Spark). It took more than 6-hours to download over my DSL line at home. And, if interrupted or failed, you have to start all over again.
3 GB!? I realize DSX desktop is more than just Jupyter, but seriously, that much more?

You need to enable virtualization. Since I have an AMD processor and Windows 10 Home edition at home, this involves setting a BIOS option on start-up, which is not well documented by HP. I guess they don't think home users need virtualization.

The log seems to indicate that the installation was successful, but there are no instructions on how to actually start DSX Desktop. The DSX icon on my desktop just takes me back to the installer. The documentation says 
"Windows Docker Toolbox only: When the installation completes, DSX Desktop will appear as a running application in your VirtualBox Manager.
You can now start DSX Desktop. If any features take long to load, restart DSX Desktop." Not.

And finally, "Give feedback" is an option in DSX Desktop itself, so you can't give feedback if you can't install it.

I'm disappointed and frustrated. Why would a so-called "Citizen Data Scientist" (I'll be a civilian after I retire) put up with this?

**Comment by T9876** [comment]
@JeremyBloom 
Have a look at issue #18 (After starting only white screen on MacOS Sierra) 
I am also using a Windows laptop; the tip with removing the settings file helped me

**Comment by nmarkey10** [comment]
@JeremyBloom Hi Jeremy, I might be able to help with getting your environment up and running.  First, to see what may have errored the install process, could you send me your log file?  It's under the Help dropdown under "Open log folder".  This will give me a better understanding of the problem.  Thank you!
