### ISSUE TITLE
Is Notebook installed correctly?

### ISSUE THREAD

**Issue by KCarm** [IBMDataScience/DSx-Desktop#27]
Hi, after removing some programs to make room on my hard drive, I downloaded the 8 GB .exe file which I thought included Jupyter Notebook.  I am now in a DSX "Notebook" trying to "Learn the Basics about DSX and Apache Spark".  I managed to download the 2015 weather file (despite the directions to it being incorrect) and am stuck on how to Load and Access the data.  It says "In the Notebook, load the data file".  Which Notebook?  Do I need to create a new Notebook to work in?  If so, how do I do that?  If I click on "my Notebooks" it says I don't currently have Notebooks.  If I click on download Notebooks it says it is another 12 GB!  Appreciate your help and guidance.  Thanks.

**Comment by nmarkey10** [comment]
Hi @KCarm, could you send me your log file?  If everything was installed properly, it shouldn't have directed you back to the page.  I can help assess what's going on in further detail if you send me the log.  This will be under the Help dropdown menu where it says "Open log folder".

**Comment by KCarm** [comment]
Sure, thanks for the help.  
[dsx-desktop.txt](https://github.com/IBMDataScience/DSx-Desktop/files/1139803/dsx-desktop.txt)

**Comment by nmarkey10** [comment]
Hi @KCarm, thank you for your log file!  It looks like the install procedure may have fired off twice, I'm still not 100% sure that's what corrupted the install but I think I might now a fix.  If you could also send me your settings file, one folder level above the log file, I may be able to manually fix it for you. Thank you for your help!

**Comment by KCarm** [comment]
Hi, thanks. When I ran docker -v in the command prompt I got... "Docker version 17.05.0-ce, build 89658be"

I am having a hard time attaching my settings file since it is not in a recognizable file format for this tool.  Maybe I should just uninstall and reinstall the whole thing per your previous comment regarding v1.1.6.

**Comment by nmarkey10** [comment]
We have fixed the problem via DM's!  The issue was solved by updating from version 1.1.5 to 1.1.6 and slightly modifying the Settings file to conform to the 1.1.6 version. (installing with 1.1.6 will take care of this)

**Comment by Debbani** [comment]
Thank you @nmarkey10  
@KCarm Closing this issue, please reopen if this problem still persists.
