### ISSUE TITLE
Not able to open the notebooks after installing dsx desktop

### ISSUE THREAD

**Issue by mkumatag** [IBMDataScience/DSx-Desktop#28]
Steps to repro:
1. Installed the dsx desktop version from https://dsx-private-cloud.mybluemix.net/public/desktop/IBM_DSX_Desktop.AppImage.

2. Version:
IBM Data Science Experience Desktop Version 1.1.6

3. Goto Community and select - Use Spark for Scala to load data and run SQL queries
4. Click on `Copy to Notebooks`
5. Then open the notebook which got created.

After this step I don't see a notebook opened and see always a spinning circle waiting to load.

I tried opening the link from container running and failed to open and see following logs:

```
[manjunath@kumatagi mldl]$ docker logs a80033461d37
already exists: /opt/notebooks
started notebook ..
[I 04:16:06.917 NotebookApp] Writing notebook server cookie secret to /home/.local/share/jupyter/runtime/notebook_cookie_secret
[W 04:16:07.269 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 04:16:07.269 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 04:16:07.284 NotebookApp] Serving notebooks from local directory: /opt/notebooks
[I 04:16:07.285 NotebookApp] 0 active kernels 
[I 04:16:07.285 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 04:16:07.285 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
tail: /tmp/nblog: file truncated
[W 05:54:18.981 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 05:54:18.982 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 05:54:18.993 NotebookApp] Serving notebooks from local directory: /opt/notebooks
[I 05:54:18.993 NotebookApp] 0 active kernels 
[I 05:54:18.993 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 05:54:18.993 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 06:16:04.316 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:16:04.367 NotebookApp] 404 GET /tree (172.17.0.1) 52.21ms referer=None
[I 06:16:19.319 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:16:19.322 NotebookApp] 404 GET /tree (172.17.0.1) 6.16ms referer=None
[I 06:16:31.278 NotebookApp] 302 GET / (172.17.0.1) 0.69ms
[I 06:16:31.310 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:16:31.313 NotebookApp] 404 GET /tree? (172.17.0.1) 5.24ms referer=None
[I 06:16:34.318 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:16:34.322 NotebookApp] 404 GET /tree (172.17.0.1) 4.32ms referer=None
[I 06:16:36.231 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:16:36.234 NotebookApp] 404 GET /tree (172.17.0.1) 4.25ms referer=http://localhost:33417/tree?
[I 06:16:38.459 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:16:38.460 NotebookApp] 404 GET /tree (172.17.0.1) 2.31ms referer=http://localhost:33417/tree
[I 06:16:49.323 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:16:49.328 NotebookApp] 404 GET /tree (172.17.0.1) 5.59ms referer=None
[I 06:17:04.318 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:17:04.319 NotebookApp] 404 GET /tree (172.17.0.1) 1.67ms referer=None
[I 06:17:19.322 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:17:19.324 NotebookApp] 404 GET /tree (172.17.0.1) 3.31ms referer=None
[I 06:17:34.316 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:17:34.317 NotebookApp] 404 GET /tree (172.17.0.1) 1.89ms referer=None
[I 06:17:49.317 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 06:17:49.319 NotebookApp] 404 GET /tree (172.17.0.1) 2.65ms referer=None
..............
..............
[I 07:10:46.367 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 07:10:46.369 NotebookApp] 404 GET /tree (172.17.0.1) 4.89ms referer=None
[I 07:11:01.366 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 07:11:01.368 NotebookApp] 404 GET /tree (172.17.0.1) 2.76ms referer=None
[I 07:11:16.366 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 07:11:16.370 NotebookApp] 404 GET /tree (172.17.0.1) 4.74ms referer=None
[manjunath@kumatagi mldl]$ 
```

**Comment by NateMoeller** [comment]
It looks like something is preventing the docker container from running. It could be a permission issue on the directory the notebook is mounting in (~/.config/ibm-dsx-desktop/Notebooks/myNotebooks). 

This issue looks similar and may be of help: https://github.com/jupyter/docker-stacks/issues/230

Could you also post your ibm-dsx-desktop log file? It can be found by going to Help -> Open log folder

**Comment by T9876** [comment]
I do have the same problem that I cannot open one of my notebooks - I can only see an infinite wheel. 

[2017-08-22 13:15:44:0353] [error] exec error: Error: Command failed: (@FOR /f "tokens=*" %i IN ('docker-machine env --shell cmd ibm-dsx') DO @%i) && docker run -d --name ibm-dsx-ana27  -p 50097:8888 -v "//c//Users/IBM_ADMIN/AppData/Roaming/ibm-dsx-desktop/Notebooks/myNotebooks":/opt/notebooks ibm-dsx-ana27:v3 /bin/bash /scripts/startup.sh
docker: Error response from daemon: Conflict. The container name "/ibm-dsx-ana27" is already in use by container "bd1ad986b42ecb47061a6b38666dc22cea35bf79bb5a432fd42da85525755360". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
[2017-08-22 13:15:44:0353] [error] stderr: docker: Error response from daemon: Conflict. The container name "/ibm-dsx-ana27" is already in use by container "bd1ad986b42ecb47061a6b38666dc22cea35bf79bb5a432fd42da85525755360". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
[2017-08-22 13:15:44:0375] [error] stderr: docker: Error response from daemon: Conflict. The container name "/rstudio-server" is already in use by container "9358cf0fa84c630e2e393a18a47dc57b967793d1a588bd0af7c23668c648b614". You have to remove (or rename) that container to be able to reuse that name.

It is not possible for me to list all existing container, not to mention to to remove or rename them. 

The jupyter/docker-stacks#230 doesn't help me as well.

**Comment by NateMoeller** [comment]
It looks like you have 2 versions of ibm-dsx-ana27 and rstudio-server trying to run. I would recommend removing your containers and restarting the DSX.

1) Open your terminal
2) Show all containers, type: docker ps -a
3) Remove the containers, type: docker rm <container_id> -f (do this for both ibm-dsx-ana27 and rstudio-server)
4) Restart DSX

**Comment by maloewer** [comment]
Hi, i seem to have that issue also. ( RHEL 7.3/ DSX Desktop 1.1.6) The issue jupyter/docker-stacks#230 got solved by setting the option z on the docker run command for mapping the directory. .
As this is done by DSX Desktop is there a way to set this option in the config . Or to start the container manually ?

**Comment by ucbdiaz2015** [comment]
Closing this as it's an older issue. If you encounter a similar issue on a newer version of DSX Desktop please open a new issue.
