### ISSUE TITLE
Downloading does not start on MacOS

### ISSUE THREAD

**Issue by jiayilei-ibm** [IBMDataScience/DSx-Desktop#3]
On MacOS(10.12.1), I am trying to download RStudio and Jupyter Notebooks, which in total has 9.99 GB. But I waited the downloading for a whole day, it did not progress a single percentage. My Internet is working normally. And this happens in two completely different networks(workplace and home).  Any ideas?

**Comment by Debbani** [comment]
@jiayilei-ibm What version of DSX Desktop do you have installed? Also, please can you attach your log file (dsx-desktop.log) so that it'll help us diagnose the issue. The log file is located in: /Users/<username>/Library/Application Support/ibm-dsx-desktop/Logs

**Comment by jiayilei-ibm** [comment]
@Debbani 
DSX Desktop version: 1.01.00(04/02/17)


[dsx-desktop.log.zip](https://github.com/IBMDataScience/DSx-Desktop/files/926070/dsx-desktop.log.zip)

**Comment by Debbani** [comment]
@jiayilei-ibm Thank you for attaching your log file. What version of the Docker tool-box do you have installed? You may have an older version of the toolbox installed. Will you be able to upgrade to the latest version of Docker toolbox or to even upgrade to Docker for Mac. instead? If you're not using Docker toolbox for any other programs, and can uninstall this, then you can simply relaunch DSX Desktop which will install Docker for Mac for your convenience. 

Additionally, please can you download the latest version of DSX Desktop - 1.01.02 (04/11/17) from http://datascience.ibm.com/desktop

**Comment by jiayilei-ibm** [comment]
@Debbani 
Newer version can start downloading, but will stuck at 10%.  Upgrading docker fixes it.
Now I can finally start DSX Desktop.
Thanks for your help!

**Comment by Debbani** [comment]
@jiayilei-ibm Glad it worked for you :) Closing this issue.
