### ISSUE TITLE
Unable to create Notebook due to docker local access for file sharing

### ISSUE THREAD

**Issue by Mobjo** [IBMDataScience/DSx-Desktop#31]
![docker file sharing](https://user-images.githubusercontent.com/18304798/28960372-a1d86b28-78fe-11e7-9b69-541a626535eb.JPG)

I've tried both local windows user and docker user, but i did not succeed. IBM does not use AzureAD domain

**Comment by nmarkey10** [comment]
Hi @Mobjo , this is a problem similar to what we've seen before.  Were you able to share your drive with Docker under the settings tab within the Docker UI?  This is required to be able to mount a local volume.

If you're having trouble finding the right username/password pare, it is likely a problem with Active Directory.  They don't let you set a password while configuring a new laptop on Windows 10, only a PIN and your fingerprint.  You will have to create a new user on your laptop (for the admin credentials) and switch to that user to give it a password.  After that you switch back you should be able to log in using that account.  The user name would be whatever user is created in your C:\Users folder.  This is only recommended if you've set up you current account with a fingerprint password, when switching between accounts, sometimes one can disappear and you won't be able to use your pin to log in again.

Step by step:
1.  Hit the Windows Button
2.  Type in Users
3.  Hit enter.
4.  Click "Manage another Account"
5.  Click "Add a new user in PC settings"
6.  Add a user using an email
7.  Log into the new user giving it a password
8.  Switch back to your original account

Let me know if it works or if you need any help.  This is a good reference article but it isn't exactly the same list of steps:
https://blogs.msdn.microsoft.com/stevelasker/2016/06/14/configuring-docker-for-windows-volumes/

**Comment by Mobjo** [comment]
Hi
Thanks a lot for responding to me. I wish I could do the steps you 
propose, but as in every large organisation (like IBM) the Administrators 
have locked down such functionality.... I cannot add user nor change local 
password. Have to stick to the PIN. Big brother has his own policy about 
the catalog services like AD, users and password. I cannot see how I can 
work around this. Any suggestions are welcome. 



Regards,

Morten 
Analytics Client Architect 


Phone: 47-9185 3095 
E-mail: morten.bjorklund@no.ibm.com 
Find me on:    


Rosenholmveien 25 
Trollasen, 1414 
Norway 



International Business Machines AS
NO 931 482 580 MVA Foretaksregisteret
Rosenholmveien 25, 1414 Trollåsen, Norway

**Comment by nmarkey10** [comment]
Hi @Mobjo.  If the proposed solution doesn't work, the other workaround would be to install using Docker Toolbox as oppose to the Docker App.  You'd have to uninstall DSX, uninstall Docker, then install Docker Toolbox and then install DSX once again.  For this, you'd have to Disable Hyper-V.  I will link how to do that and also the link to Docker Toolbox!

Disabling Hyper-V: http://www.poweronplatforms.com/enable-disable-hyper-v-windows-10-8/

Docker Toolbox: https://www.docker.com/products/docker-toolbox

**Comment by Mobjo** [comment]
Hi @nmarkey10 
The last proposed work around with with disabling Hyper-V and Docker Toolbox worked fine. Thanks a lot.
