### ISSUE TITLE
NameError: name 'spark' is not defined

### ISSUE THREAD

**Issue by am8042** [IBMDataScience/DSx-Desktop#33]
Hi,
I have installed DFX Desktop and I was assuming that Spark will be installed along with it, but sounds I was wrong. Should I install Spark on my computer separately? And if I do, would that be working fine with DSX?

Thanks,
Asghar

**Comment by Debbani** [comment]
@am8042 Have you installed **Anaconda + Spark** or one of the other Notebook images? Please can you go to the Settings -> General tab to find out what type of the Notebook image you've installed. You'll not need to install Spark separately. If you've one of the other non-spark images downloaded, you can uninstall just the notebook image and install the one that you're looking for.

**Comment by am8042** [comment]
Hi, Yes I have Anaconda (Python 2.7) installed there. But there is no Spark
there.


Asghar Mohammadi
Data Scientist
Center for Health Informatics & Analytics
Room 4M412, Faculty of Medicine
Memorial University of Newfoundland
Phone: 709-864-6611

**Comment by Debbani** [comment]
@am8042 That's correct, this notebook image does not have Spark. Please follow the steps described above to uninstall the notebook image that you've, and install the **Anaconda + Spark
<img width="1019" alt="screen shot 2017-08-17 at 6 27 48 am" src="https://user-images.githubusercontent.com/16294973/29414702-7508b0d2-8315-11e7-8f90-39991862214c.png">
** image instead.
