### ISSUE TITLE
404 Page found 

### ISSUE THREAD

**Issue by zzdztgithub** [IBMDataScience/DSx-Desktop#36]
I successfully installed DSX desktop and created a notebook for testing. But after ten minutes, when I restart docker, dsx desktop, and tried to enter the same notebook, I found this page:

![image](https://user-images.githubusercontent.com/22535254/30122223-61d98184-9360-11e7-8d4b-5e4f5a4bd16c.png)

How could I fix it?

**Comment by sahilshah2211** [comment]
Can you remove the docker container and restart the app ? Also can you send the log file too? You can find the log file here: https://datascience.ibm.com/docs/content/desktop/troubleshoot.html

**Comment by ucbdiaz2015** [comment]
Closed this as it's an older issue. If you encounter a similar issue on a newer version of DSX Desktop, please open a new issue.
