### ISSUE TITLE
Data connections missing

### ISSUE THREAD

**Issue by Davin-IBM** [IBMDataScience/DSx-Desktop#4]
One of the community notebooks that comes bundled in the Desktop version (AnalyzeEnergyConsumptionInBuildings.ipynb) talks about downloading .csv files and adding them as data sources via a Data icon.  I can find no such icon.  See screenshots attached.

![DSX Desktop](https://cloud.githubusercontent.com/assets/26653664/25142452/e1fb2930-2434-11e7-9074-04997c6dcee1.png)

![Notebook instructions to add data sources](https://cloud.githubusercontent.com/assets/26653664/25142369/a2594a78-2434-11e7-9160-a8b9f2dc1394.png)

**Comment by Davin-IBM** [comment]
You can add data assets at the "My Notebooks" level, but as far as I know, there isn't a way to do this while _inside_ a notebook in DSX Local. 

![screen shot 2017-04-18 at 12 58 23 pm](https://cloud.githubusercontent.com/assets/26653664/25143065/106feb1e-2437-11e7-8036-6d3a210b5e1e.png)

**Comment by Davin-IBM** [comment]
I was finally able to connect to my data assets by prepending `./assets/` to the file name (this is documented here http://datascience.ibm.com/docs/content/desktop/loaddata.html).   The working code is in the following screenshot:

![screen shot 2017-04-18 at 1 30 48 pm](https://cloud.githubusercontent.com/assets/26653664/25144297/49f2e072-243b-11e7-9089-ee2b6dc05b16.png)

Accessing data assets from within a notebook is fundamental and needs to be simple and intuitive.   The instructions in the notebook that ships with this product do not align with the features in the user interface (currently in beta), causing confusion which will hopefully be remediated prior to GA.

Hope it helps!

**Comment by Debbani** [comment]
@Davin-IBM The latest version of DSX Desktop (Version: 1.01.03) now has the Data icon from where you can now add data assets and insert the code to use these assets.
