### ISSUE TITLE
Install failed, complaining no Internet connection

### ISSUE THREAD

**Issue by weirending** [IBMDataScience/DSx-Desktop#40]
[dsx-desktop.log](https://github.com/IBMDataScience/DSx-Desktop/files/1343120/dsx-desktop.log)

Install failed with the following message:
"
Internet connection needed
You need an internet connection to Install Data Science Experience Desktop. Connect to the internet to continue.
"

The log file seems showing connection to "151.101.48.133:403" failed. Any idea how to resolve this? Change firewall setting? Full log file is attached. 

Thanks

Weiren

**Comment by sahilshah2211** [comment]
Can you check if the IBM_DSX_Desktop.exe is allowed access to the network? Checking firewall setting also seems to be a good idea.

**Comment by ucbdiaz2015** [comment]
Closed this as it's an older issue. If anyone encounters a similar issue on a newer version of DSX Desktop, please open a new issue.
