### ISSUE TITLE
Cannot import local python file

### ISSUE THREAD

**Issue by touchaponk** [IBMDataScience/DSx-Desktop#41]
I'm using IBM DSX Desktop for macOS and I need to import python file into my python notebook. I tried importing just like normal csv file but that doesn't seem to do the trick.

**Comment by sahilshah2211** [comment]
Can you elaborate on this?  A normal import should work if you give a proper path. Can you send the information/snippets of code to reproduce this?

**Comment by ucbdiaz2015** [comment]
Closed this as it's an older issue. If you encounter a similar issue on a newer version of DSX Desktop, please open a new issue.
