### ISSUE TITLE
R Studio not start in IBM Data Sciense Experience Desktop

### ISSUE THREAD

**Issue by JuanBohorquezC** [IBMDataScience/DSx-Desktop#43]
I update the version of the docker, and now do not start the applications like R Studio, it stays in the circle turning, Uninstall and Install the Data Science Experience and the problem persists

**Comment by praneethbellamkonda** [comment]
It happened with me as well only when I opened R Studio.

**Comment by sahilshah2211** [comment]
@JuanBohorquezC  Can you send me your log file. You can find instructions to get to the log file here: https://datascience.ibm.com/docs/content/desktop/troubleshoot.html
@praneethbellamkonda  Can you delete the existing rstudio-server container. Run `docker rm -f rstudio-server`. Then go to RStudio to see if the problem still persists. If it still persists can you also send me your log file.

**Comment by ucbdiaz2015** [comment]
Closed this as it's an older issue. If you encounter a similar issue on a newer version of DSX Desktop, please open a new issue.
