### ISSUE TITLE
Downloaded DSX Desktop for Mac.  Just endless swirling when I try to do anything

### ISSUE THREAD

**Issue by jjgrossman** [IBMDataScience/DSx-Desktop#46]
My install went fine, however when trying to do anything in the app, I mostly get endless swirling image.  This includes trying to: 
"View all projects"
"Open a jupyter notebook"

When I am finally able to get to a project I created: 
Trying to add a notebook asset gets to "Launching Jupyter" message, but then endless swirling without ever being able to open a notebook. 

Any suggestion on debugging this is appreciated. 

Thanks,
Jeff

**Comment by Debbani** [comment]
@jjgrossman Please can you execute a **docker ps -a** in a terminal window and please paste the output here. I'd like to see if your Jupyter image is running.

**Comment by jjgrossman** [comment]
Thanks for the help, Debbani.  Seems like despite the app running, docker seems to not be??... : 

Response in terminal: 
_Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?_

**Comment by Debbani** [comment]
@jjgrossman Was docker installed during the DSX Desktop installation, or did you have docker already installed before? What version of docker do you have installed? Please can you restart your docker to see if that fixes the issue.  
<img width="235" alt="dockerrestart" src="https://user-images.githubusercontent.com/16294973/32780319-a89d8884-c8f5-11e7-8848-e3bf0a3a351d.png">

**Comment by jjgrossman** [comment]
I believe I already had docker installed. When DSX did the installation, it showed as a green checkbox.  

Docker version 17.09.0-ce, build afdb6d4. 

Restarted docker and DSX is still hanging on notebook creation. Thanks again.

**Comment by ucbdiaz2015** [comment]
@jjgrossman If you're still seeing this issue, please try downloading the latest version of DSX Desktop (V1.2.0) and let us know if the problem persists.
