### ISSUE TITLE
1.2.0 Installables are NOT working for Windows (7 Prof is what I am using)

### ISSUE THREAD

**Issue by swagadre** [IBMDataScience/DSx-Desktop#51]
DSX Desktop 1.2.0 Installables are NOT working for Windows (7 Prof is what I am using).

It hangs at Downloading Docker.

Any work around ? Any specific (Windows) platform on which it has worked ?

Regards
Swanand

**Comment by Debbani** [comment]
@swagadre DSX Desktop should work on both Windows 7 and Windows 10. Please can you send us your log file (Help->Open log folder) so that we can diagnose what the issue is with your installation.

**Comment by swagadre** [comment]
@Debbani Attaching the logs.
There will be some errors related to docker and Oracle Virtual Box, but after cleaning up the system those error messages are not appearing .
[dsx-desktop.log](https://github.com/IBMDataScience/DSx-Desktop/files/1584719/dsx-desktop.log)

**Comment by Debbani** [comment]
@swagadre Your log file indicates that you had canceled installation in the middle of installation and looks like your ibm-dsx vm may be in an unstable state. Please can you delete/remove your ibm-dsx vm and re-install the images. Please let me know if you're still running into issues.

**Comment by swagadre** [comment]
@Debbani Thanks for the response.

I removed ibm-ds VM from VBox and then restarted the installation process.
I was able to complete the installation and launch the application.

Thank you very much !! for your prompt response. This is very helpful.

Regards
