### ISSUE TITLE
Confusion about which version to install for Windows 7

### ISSUE THREAD

**Issue by traincroft** [IBMDataScience/DSx-Desktop#53]
The information on the IBM webpages is diverse and confusing. It would be very helpful to have a "guide" or a "map" about the differences between cloud vs. desktop installations. 

This is particularly true for Windows 7 installation. I tried to follow these instructions, and found myself spending more than 3 hours (!) to download a version that would only work on Linux. Fortunately, I found someone on the DSX staff (there was no direct consultation offered) who told me that I had followed a decision-path down to Linux-only information, so I could stop that useless effort. (But why is the installation information so confusing, as to allow me to make that mistake? and why can't we identify the user's OS, and prevent them from spend enormous time and diskspace on the wrong installation package?)

Newcomers need a much clearer set of advices and instructions. These kinds of complexities can drive customers away.

thank you,
--michael

**Comment by Debbani** [comment]
@traincroft I'd like to understand the issue that you ran into better. There are 3 buttons - one for Windows, Mac and Linux. Did you download the image for Linux instead of the one for Windows? 
Our documentation does go over the different flavors of the offering: https://datascience.ibm.com/docs/content/getting-started/welcome-main.html?audience=cloud&context=analytics

**Comment by traincroft** [comment]
Dear Debbani,

Thank you for asking.

There are several entry-points to the DSX documentation and downloads.  If
one begins ag
http://pokgsa.ibm.com/projects/d/dsxdoctest/local/install.html

**Comment by jerry1100** [comment]
Hi @traincroft, thanks for your concern.

I think nowadays, figuring out where and how to download DSX Desktop is relatively straightforward. For example, if you [google "dsx desktop download"](https://www.google.com/search?q=dsx+desktop+download) the first link is our GitHub and the second link is the [DSX Desktop website](https://datascience.ibm.com/desktop), both of which offer clear instructions on how to download it.

That said, do you have any other concerns? If not, I'll go ahead and close this issue.

**Comment by traincroft** [comment]
Thank you very much!  Yes, please close this issue.

all the best,
--michael (aka traincroft)
-----
Michael Muller, PhD, IBM Research, Cambridge MA USA
ACM Distinguished Scientist
ACM SIGCHI Academy
IBM Master Inventor
