### ISSUE TITLE
IBM_DSX_Desktop-1.2.2 support python 3 with spark

### ISSUE THREAD

**Issue by JohnPhilipPearson** [IBMDataScience/DSx-Desktop#54]
I was using a prior IBM_DSX_Desktop version that supported python 3 with spark.
I downloaded IBM_DSX_Desktop-1.2.2.dmg and about to install, does not seem to support python 3 with spark.

Thank you,
JP

**Comment by sahilshah2211** [comment]
We are bringing in Anaconda with Python3 and spark in the next release of DSX Desktop.

**Comment by JohnPhilipPearson** [comment]
Is there a road map with release dates and what you hope to accomplish in each release?
