### ISSUE TITLE
Cannot press Continue in DSX Installation Settings

### ISSUE THREAD

**Issue by MenonH** [IBMDataScience/DSx-Desktop#55]
![image](https://user-images.githubusercontent.com/28547748/36760395-a47b2aae-1be8-11e8-9d8b-a09715672424.png)

Not sure what the issue is, Windows 7.

**Comment by sahilshah2211** [comment]
@MenonH  Please can you send us your log file (Help->Open log folder), so that we can diagnose what the issue is. Also I would recommend in closing the app and reopening.

**Comment by MenonH** [comment]
Hi, this is the log file. Reopening doesn't work. Thanks for the help.

**Comment by jerry1100** [comment]
Hi @MenonH, sorry for the late response.

Were you able to resolve this issue? Also, it doesn't seem like your logs were included, so please include that if the issue still persists.
