### ISSUE TITLE
DSX Desktop (with RStudio) -- Unable to load R packages

### ISSUE THREAD

**Issue by cgoo4** [IBMDataScience/DSx-Desktop#57]
I installed DSX Desktop with RStudio on a Windows 7 machine. When DX was working yesterday, i.e. prior to the spinning circle in issue #56, I was unable to load new packages, e.g. lubridate, and got the error below. And when I checked for package updates, I got the message `all packages are up-to-date`, but the error below does suggest it needs a newer version of Rcpp.

```
installing to /user-home/_global_/R/lubridate/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘Rcpp’ 0.12.9.2 is already loaded, but >= 0.12.13 is required
ERROR: lazy loading failed for package ‘lubridate’
* removing ‘/user-home/_global_/R/lubridate’
Warning in install.packages :
  installation of package ‘lubridate’ had non-zero exit status

The downloaded source packages are in
  ‘/tmp/RtmpIV4HWl/downloaded_packages’
```

I tried `install.packages("Rcpp")` which returned the message:

```
Error in unloadNamespace(pkg_name) : 
  namespace ‘Rcpp’ is imported by ‘httpuv’, ‘reshape2’, ‘tidyr’, ‘bindrcpp’, ‘tibble’, ‘htmltools’, ‘dplyr’, ‘plyr’ so cannot be unloaded
```

I tried `remove.packages("Rcpp")` or removing the packages above, and got the following message, and they remained in the Packages view.

```
Removing package from ‘/user-home/_global_/R’
(as ‘lib’ is unspecified)
Error in remove.packages : there is no package called ‘Rcpp’
```

(I've also posted this on Stackoverflow [here](https://stackoverflow.com/questions/49212046/unable-to-install-new-r-packages-in-dsx-desktop) .)

**Comment by cgoo4** [comment]
I also tried re-pointing the package library per below (the path of my R installation), but it stays pointed at the library from the DSX install. 

```
.libPaths("C:/Program Files/R/R-3.4.4/library") 
.libPaths() 
[1] "/user-home/_global_/R" "/usr/lib64/R/library" [3] "/usr/share/R/library"
```

**Comment by jerry1100** [comment]
Hi @cgoo4, sorry for the late reply.

I'm not too familiar with RStudio and how we're building the RStudio image, so let me ask my coworker for some help with this.

**Comment by jerry1100** [comment]
@prashant182, can you please look into this?

**Comment by prashant182** [comment]
Sure @jerry1100 . Let me see if I can find something about this issue.

**Comment by jerry1100** [comment]
Hey @cgoo4, got some news for you:

DSX Desktop is going to be discontinued and a new desktop application (which I'm working on) will take its place in the coming months.

I'll continue to monitor the issues here in case there are some that can still be resolvecd, but it'll be less frequent because I'm busy working on the new app.

As for now, I'm closing this because there won't be any updates to the RStudio image.
