### ISSUE TITLE
Zeppelin installed even when I don't want it to be

### ISSUE THREAD

**Issue by paulzikopoulos** [IBMDataScience/DSx-Desktop#59]
I did not check the box to install Zeppelin; in settings it says that (I can click install) but the option shows up in the menu in DSX Local; what's more I even click on it and it takes me through a process to create a Zeppelin notebook.

**Comment by jerry1100** [comment]
Hi @paulzikopoulos, all the tools (Jupyter, RStudio, and Zeppelin) show up in the sidebar regardless of whether you have them installed or not.

When you click on Jupyter or Zeppelin, it will take you to the "Create Notebook" page even if you don't have Jupyter or Zeppelin installed. However, if you actually try and create a notebook, it won't let you and instead prompts you to install the tool first, as shown below.
![screen shot 2018-04-12 at 8 39 50 pm](https://user-images.githubusercontent.com/18181641/38715931-fc18cd58-3e92-11e8-831d-c0dbc4361d4c.png)

**Comment by jerry1100** [comment]
@paulzikopoulos update for you:

DSX Desktop is going to be discontinued in favor of a new desktop application based off of both DSX and Watson Studio.

I'm closing this issue because there's nothing I can do to fix this.
