### ISSUE TITLE
Install Hangs on Win7 at 10%

### ISSUE THREAD

**Issue by tonyd-ibm** [IBMDataScience/DSx-Desktop#6]
I'm trying to install the windows version, but it won't go past the 10% (Checking Docker Status) no matter how long I wait.  This is my 3rd attempt.  I've checked the dsx-desktop.log and nothing in there other than this:

[2017-04-26 08:54:47:0794] [info] InitialPage() container
[2017-04-26 08:54:48:0126] [info] Docker was found
[2017-04-26 08:54:50:0766] [info] calling tarPathExists
[2017-04-26 08:54:50:0766] [info] calling registryIniExists
[2017-04-26 08:54:50:0766] [info] registry.ini does not exist
[2017-04-26 08:54:50:0766] [info] tarPath is not defined
[2017-04-26 08:54:53:0587] [info] calling tarPathExists
[2017-04-26 08:54:53:0587] [info] calling registryIniExists
[2017-04-26 08:54:53:0587] [info] registry.ini does not exist
[2017-04-26 08:54:53:0588] [info] tarPath is not defined

**Comment by nmarkey10** [comment]
Hi @tonyd-ibm, this is an odd error, it looks like it's cycling through, checking for your tarPath.  Are you using a registry.ini file in your settings AppData folder?  This is a feature that should only be used if the user adds that file to their file system.  It would be under %AppData%\ibm-dsx-desktop in your file system.  Also, it would be helpful to know what version of the beta you're on.  This can be checked under the help dropdown within the app and can also be found appended to the setup file name.  

Also, is this your full log?  There seems to be a lot missing that we should be printing out.  There is a new build that we are expecting to push out tomorrow that has a lot of various fixes, including how we handle tarPaths and more comprehensive log printouts.  Thank you for your help!

**Comment by tonyd-ibm** [comment]
@nmarkey10 thanks for your reply.  No, I do not have a registry.ini file in my AppData folder at all.  I am using version 1.01.02 (4/11/17).  Yes, this is my full log.  It gets to 10% and then just stops.  I shut everything else down and basically let it run all night.  got up this morning and it was still just sitting at 10%.

I will check out the new build when it comes out and hopefully I'll have better luck :)

Thanks for your help.

**Comment by tonyd-ibm** [comment]
@nmarkey10 quick update.  I was able to get by the issue I was having by uninstalling and re-installing my Docker Toolbox.  apparently I must have had a few missing or older drivers that weren't working correctly.  once I did that, the install has moved on (On 56% as I type this).

**Comment by nmarkey10** [comment]
@tonyd-ibm ah, awesome!  Thanks for the update.  The Docker Toolbox support after popular demand and was added to allow Windows users the option to continue using their flavor of Docker.  The Docker app does not work on versions of Windows older than 8.  This has spawned various issues where we are supporting different software to work in conjunction with our app but the version is subjective to what the user has.  Again, thank you for the update and help!  It helps us make a more robust and error proof app.

**Comment by aruizga7** [comment]
Same issue for me. I have Windows 7 and I re-installed Docker Toolbox and Virtual box but it is still stuck in 10%

**Comment by nmarkey10** [comment]
@aruizga7 we pushed a new beta version last week, it has a lot of bug fixes, updates and overall changes.  Please try installing with the newer version.  If you have any questions or face anymore problems please ping me and I will respond when I can.  Thanks for your patience.  

Download Page: https://datascience.ibm.com/desktop

**Comment by Debbani** [comment]
@tonyd-ibm Closing this issue, please re-open if this problem still persists.
