### ISSUE TITLE
Shiny integration not opening web browser ... pop-up blocked but no URL or browser

### ISSUE THREAD

**Issue by paulzikopoulos** [IBMDataScience/DSx-Desktop#60]
When I execute it, I see it starting and its getting pop-up blocked; I only can tell that when I stop it and it asks me if I want to retry. I want to add in a pop-up exception but I can't see where a URL is, and the pop-up browser doesn't have controls. Is there a way to fix this?

**Comment by jerry1100** [comment]
Hi @paulzikopoulos, thanks for reporting this. This is a known issue and we have plans on fixing it (albeit it's not a high priority for us right now).

Right now, only "Run in Viewer Pane" works, as shown below.
![screen shot 2018-04-12 at 8 33 02 pm](https://user-images.githubusercontent.com/18181641/38715570-cf499354-3e90-11e8-95be-812d2e35a74c.png)
