### ISSUE TITLE
DSX desktop installation is stuck at “dockerPull entered” phase

### ISSUE THREAD

**Issue by weirending** [IBMDataScience/DSx-Desktop#61]
Installing DSX Version: 1.2.2 on a Windows 7 VM, it is stuck at "dockerPull entered" phase shown in dsx-desktop.log:

> ......
> [2018-03-27 16:01:12:0535] [info] Regenerating the certificates
> [2018-03-27 16:01:13:0258] [info] Internet Connection reconnected, setting isInternetBad to false
> [2018-03-27 16:01:13:0364] [info] Internet Confirmed true ++ true
> [2018-03-27 16:01:16:0831] [debug] #OS: Windows
> [2018-03-27 16:01:16:0831] [info] Confirming Docker Host for Windows
> [2018-03-27 16:01:17:0365] [debug] #GENERATE WINHOST
> [2018-03-27 16:01:18:0149] [info] Passed storage check, prefix: B
> [2018-03-27 16:01:18:0149] [info] dockerPull entered.

**Comment by jerry1100** [comment]
Hi @weirending, sorry for the late reply.

I don't see anything wrong with the snippet you included. I recommend installing v1.2.3, which we released not too long ago. It has an improved installer so hopefully whatever issue you're facing won't be there in that version.

If that doesn't work for some reason, please post the full logs.

**Comment by jerry1100** [comment]
__Update__: Install v1.2.4, which has a much improved installer. You can download it here: https://www.ibm.com/account/reg/signup?formid=urx-32209.

Let me know if that works.
