### ISSUE TITLE
Not able to download the Desktopversion for Windows.

### ISSUE THREAD

**Issue by rahulrajvn** [IBMDataScience/DSx-Desktop#69]
https://datascience.ibm.com/desktop >> Download for Windows >> Give credentials >>  I agreee Page >> Thank-you Page

Even after reaching the thank-you page the download of the package didn't start.

**Comment by jerry1100** [comment]
Hi @rahulrajvn, sorry about that. The download link has changed and the website hasn't been updated with the new link yet. The new link is https://www.ibm.com/account/reg/signup?formid=urx-32209.

Let me know if that works for you.

**Comment by jerry1100** [comment]
Closing since the download links have been updated on the website (https://datascience.ibm.com/desktop).
