### ISSUE TITLE
RStudio not starting (Win10)

### ISSUE THREAD

**Issue by jmsidhu71** [IBMDataScience/DSx-Desktop#7]
After downloading packages for RStudio in DSX, Rstudio does not start (spinning wheel).  Have restarted both machine and docker to no avail.
[log.txt](https://github.com/IBMDataScience/DSx-Desktop/files/966831/log.txt)

**Comment by nmarkey10** [comment]
Hi @jmsidhu71 , I believe you may have sent us the wrong log file.  Our app has a Help dropdown that will open up the folder where we store our log file.  If you could shoot me that log file back I could help address whatever issue you might have.  Thanks!

**Comment by jmsidhu71** [comment]
Trying again.

**Comment by jmsidhu71** [comment]
Trying again.
[dsx-desktop - Copy.txt](https://github.com/IBMDataScience/DSx-Desktop/files/972309/dsx-desktop.-.Copy.txt)

**Comment by nmarkey10** [comment]
@jmsidhu71 The newest version has been pushed! There are a lot of updates and changes that went into 1.1.4 and it should solve the issues. Before installing the new version, please make sure you uninstall the current one, using the app uninstaller under the settings menu within the app itself. Thank you for your patience, please let me know if you run into any problems or have any questions.

**Comment by Debbani** [comment]
@jmsidhu71 Closing this issue. Please feel free to reopen this if you're still running into issues.
