### ISSUE TITLE
Dont find search option in Community

### ISSUE THREAD

**Issue by yogeshkulkarni11** [IBMDataScience/DSx-Desktop#79]
Dont find a option to search the samples in the community area.
![ibm dsx issue](https://user-images.githubusercontent.com/29195015/44620635-7a58ff80-a8b5-11e8-9ade-171cda6ac998.png)

**Comment by jerry1100** [comment]
You're right, there is no search feature.

Here's a table of all the sample notebooks as well as a description of each. This is straight from DSX Desktop.

| Name | Description |
| --- | --- |
| Analyze energy consumption in buildings | This Python notebook shows you how to use analytics to determine the factors that contribute to energy inefficiency in buildings and to help develop strategies to reduce energy consumption and greenhouse gas emissions. |
| Analyze open data sets with DataFrames | In this notebook, you'll learn how to use open data from the data sets on the Data Science Experience home page in a Python notebook. You will load, clean, and explore the data with pandas DataFrames. |
| Approximating a Function using Deep Learning | This tutorial examines the claim that a neural network can approximate any mathematical function |
| Balance production of pasta | This tutorial includes everything you need to set up IBM Decision Optimization CPLEX Modeling for Python (DOcplex), build a Mathematical Programming model, and get its solution by solving the model on the cloud with IBM ILOG CPLEX Optimizer. |
| Benders decomposition with decision optimization | This tutorial includes everything you need to set up decision optimization engines, build a mathematical programming model, and then use the Benders decomposition on it. |
| Building steel coils | This tutorial includes everything you need to set up decision optimization engines, and build constraint programming models to optimize the steel mill slab design problem solution. |
| Earthquake Demo with Logistic Regression | This tutorial will show you how to model and visualize earthquake data using a Zeppelin Notebook |
| House Building with worker skills | This tutorial includes everything you need to set up decision optimization engines, and build constraint programming models to efficiently assign construction tasks to workers of different skill levels when you build houses in different locations. |
| How to make targeted offers to customers? | This tutorial includes everything you need to set up IBM Decision Optimization CPLEX Modeling for Python (DOcplex), build a Mathematical Programming model, and get its solution by solving the model with IBM ILOG CPLEX Optimizer. |
| Incremental modeling with decision optimization | This tutorial includes everything you need to set up decision optimization engines, build a mathematical programming model, then incrementally modify it. |
| Learn basics about notebooks and Spark | This notebook introduces you to the basics of analytics notebooks and explains what Apache Spark is and how to use Spark in notebooks. The notebook shows you how to load data into the notebook, parse and explore the data, run queries on the data to extract information, plot your analysis results, and save your result in Object Storage. |
| Maximize oil company profits by using decision optimization | This notebook includes everything you need to set up decision optimization engines.  You will learn to build mathematical programming models to determine the best methods of maintaining a high quality product for oil company customers while maximizing profits. |
| Model a Golomb ruler using DO | This tutorial includes everything you need to set up decision optimization engines, build constraint programming models. |
| Modeling Weather Geographies using Scikit-Learn | This tutorial explores predicting max daily temperatures using Scikit-learn |
| Modeling Weather Geographies using XGBoost | This tutorial explores predicting max daily temperatures using XGBoost |
| Organize product delivery using DO | This tutorial shows how to set up Decision Optimization engines and build a constraint programming model to efficiently organize product delivery to customers using a single truck. All data and instructions that you need to model and solve this problem are included. |
| Sched Square | This tutorial includes everything you need to set up decision optimization engines, and build constraint programming models to optimize the Sched Square solution. |
| Sudoku | This tutorial includes everything you need to set up decision optimization engines, build constraint programming models. |
| The Unit Commitment Problem | This tutorial includes everything you need to set up IBM Decision Optimization CPLEX Modeling for Python (DOcplex), build a Mathematical Programming model, and get its solution by solving the model on the cloud with IBM ILOG CPLEX Optimizer. |
| Train and predict with Python machine learning | This notebook shows you how to use python machine learning libraries and services from DSX Local to train, save, deploy and evaluate a model and make prediction for new data. |
| Train and predict with Scala machine learning | This notebook shows you how to use scala machine learning libraries and services from DSX Local to train, save, deploy and evaluate a model and make prediction for new data. |
| Use DO to schedule sports games | This tutorial includes everything you need to set up decision optimization engines, build mathematical programming models, and arrive at a good working schedule for a sports league's games. |
| Use Lagrangian relaxation | This tutorial includes data and information that you need to set up Decision Optimization engines and build mathematical programming models to solve a Generalized Assignment Problem using Lagrangian relaxation. |
| Use Python to load data and run queries | This notebook introduces basic Spark concepts and helps you to start using Spark for Python. |
| Use R to load data and run queries | This notebook introduces basic Spark concepts and helps you to start using Spark for R. |
| Use Scala to load data and run queries | This notebook introduces basic Spark concepts and helps you to start using Spark for Scala. |
| Use deep learning for image classification | This Python notebook shows you how to use deep learning to build a classification model that maps images of single digit numbers to their corresponding numeric representations. |
| Using the Progress Callbacks with CPLEX Optimizer | This tutorial includes everything you need to set up decision optimization engines, build a mathematical programming model, then use the progress callbacks to follow the progress, capture the intermediate solutions and stop the solve on your own criteria. |
| Visualize car data with Brunel | The Brunel Visualization language makes it easy to build interactive charts and diagrams that you can deploy rapidly. This notebook contains the steps and code to get you started with visualizing data with Brunel. |
| Work with a remote Spark Sample One | IBM DSX Local provides the interface for Python notebooks to work with an existing remote Spark through HTTP connection and user-friendly sparkmagic commands. This sample notebook shows how to send a simple request to remote Spark. |
| Work with a remote Spark Sample Three | IBM DSX Local provides the interface for Python notebooks to work with an existing remote Spark through HTTP connection and user-friendly sparkmagic commands. This sample notebook shows how to work with remote Spark using the Livy Spark kernel. |
| Work with a remote Spark Sample Two | IBM DSX Local provides the interface for Python notebooks to work with an existing remote Spark through HTTP connection and user-friendly sparkmagic commands. This sample notebook shows how to send an SQL request to remote Spark to get a DataFrame. |

Hope this helps.
